= Fendo to-do list

.2013-06-04:

In <fendo.parser.fs>: Flag the first markup of the current line, in
order to use '--' both for nested lists and for delete.

.2013-06-08:

In <fendo.data.fs>, can 'current_page' be used instead of ''data'?

.2013-08-14:

Choose better names for different meanings of "content":
1) raw content of the page (printable content and markups)
2) printable content only, not executable markups

.2013-08-15:

defered words at the start (and end?) of tags,
to let the website application insert hooks.

.2014-03-03:

In <fendo.data.fs>:

----
: pid$>source  ( ca1 len1 -- ca2 len2 )
  \ Convert a page id to a source filename.
  \ xxx not used
  -anchor! +forth_extension +source_dir
  (* 2014-03-03: This word was tried in '(required_dat<pid$)', but
  adding the path to the filename makes the pages to be included into
  the list of included files (shown by '.included') with an absolute
  path. The solution is: the application has to add 'source_dir' to
  'fpath'.  *)
  ;
----

.2014-03-03:

Write an addon to create a list of rencent changes?

.2014-03-03:

Inform the Gforth list about this:

----
: traversed_pid  ( ca len -- )
  \ ca len = pid
  (traversed_pid) 0= if  \eof  then
  ;
: traverse_pids  ( xt -- )
  is (traversed_pid)  create_pids_file  
  \ pid_file$ included  \ xxx fixme this causes problems:
  \   *** glibc detected *** gforth: free(): invalid pointer: 0xb69fb7f0 ***
  \   Aborted.
  pids_file$ slurp-file evaluate  \ xxx this works
  ;
----

.2014-03-08:

New:

meta markups ~- and ~+ to change the separation of the next item.

.2014-03-12:

Fix:

Add tag list to the project descriptions.  This fails with projects of a
different language than the current language, because tag links are built
using the current language: a link to the English tag "X" built in a Spanish
page will try to link to the missing page "es.etiqueta.X" instead of
"en.tag.X".

.2014-03-12:

finish <fendo.addon.tag_cloud_by_regex.fs>

.2014-03-12:

Improvement:

Implement the automatic use of the alternative-language metadata (title.en,
description.eo, etc) How? A special metadatum? Defer every metadatum?

Could be done also in 'tune_local_link'.

.2014-04-07:

Idea:

Implement author and title for block quotes, like Asciidoctor, e.g.:

<[ s" Miguel de Cervantes" quote_author! s" El quijote" quote_title! ]>
""""
En un lugar de la Mancha.
""""

That would render a proper footer under the quote block.
At the end of the block, the variables must be reseted.

.2014-07-13:

Idea:

Update the 'modified' metadatum with the modification time of every
source code file included into the page. This way, the target
modification time will be that of the most recent source code, even if
the page is older. This way the FTP updates will be easier. [Update,
2014-11-01: this has a drawback: a trivial modification of a source
file would force the date of the webpage.]

For the same reason, update the 'modified' metadatum of tag pages with
the most recent time of any of its tagged pages. [Update, 2014-11-01:
not very useful.]

.2014-10-20:

Bug:

In 'highlighted_####-zone' (<fendo.markup.fendo.code.fs>),
'source_code_finished' must be called at the end, but it's defined in
<fendo.addon.source.code.fs>.

.2014-10-25:

Problem in fendo.data.fs:

----
: data_already_got?  ( -- 0 | xt +-1 )
  \ XXX FIXME this check means pids of draft can not be created...
  \ XXX ...but they are useful to do some checkings, e.g. in
  \ Fendo-programandala's related_pages.
  current_pid$ known_pid$?
  ;
----

.2014-11-01:

Fix:

(Problem since 2014-03.)

Link parsing fails when the link text spans the next line.

Link parsing fails when "]]" is at the start of a new line!

Make it possible to split links in severals lines of text.

.2014-11-06:

Idea:

Create an addon to share the URL of the current page. Example:

Current URL:
http://www.iconarchive.com/show/whistlepuff-icons-by-firstfear/programs-icon.html
Share links:
http://www.facebook.com/sharer.php?u=http%3A%2F%2Fwww.iconarchive.com%2Fshow%2Fwhistlepuff-icons-by-firstfear%2Fprograms-icon.html&t=Programs+Icon+%7C+Whistlepuff+Iconset+%7C+firstfear
http://twitter.com/home?status=http%3A%2F%2Fwww.iconarchive.com%2Fshow%2Fwhistlepuff-icons-by-firstfear%2Fprograms-icon.html
https://plus.google.com/share?url=http%3A%2F%2Fwww.iconarchive.com%2Fshow%2Fwhistlepuff-icons-by-firstfear%2Fprograms-icon.html
http://www.blogger.com/blog_this.pyra?t=&u=http%3A%2F%2Fwww.iconarchive.com%2Fshow%2Fwhistlepuff-icons-by-firstfear%2Fprograms-icon.html&n=Programs+Icon+%7C+Whistlepuff+Iconset+%7C+firstfear

.2014-11-07:

Check:

'link_text_as_attribute?' is the condition of an unbalanced '[if]' in <fendo.links.fs>.
It has been fixed, but it has to be tested.

Idea:

Remove double spaces in '(unmarkup)' (defined in <fendo.markup.common.fs>)?

.2014-11-17:

Change:

First, rename 'pid$>pid#'.
Second, rename 'pid$>data>pid#' to 'pid$>pid#'.

Bug:

When 'lonely_tags_link_to_content' is on, every shortcut than converts
a virtual tag page to the actual content page has a side effect: it
increases the count of the correspondent tag!

It will be easier to deactivate this system.

No, the problem is the virtual tag page exists!

.2014-11-27:

Fix:

Links to anchors in the same page are not recognized!  See
<es.programa.sbim.html>.

.2014-11-27:

In 'tune_local_link' (<fendo.links.fs>), fetch alternative language
title and description.

'link_anchor+' should not be
in <fendo.data.fs>'s 'target_file',
but in an upper level.

.2014-12-02:

Añadir hreflang a todos los enlaces de Atom.

.2014-12-02:

Idea: bandera para crear versión local. Por ejemplo, para adaptar el
atributo 'xml:base=' usado en Atom. ¿Sirve de algo? Si 'xml:base=' no
se usa, ¿son los enlaces locales relativos al lugar del propio Atom?

.2014-12-05:

Change the properties system: make it similar to tags: make properties
executable; they should trigger a flag.
