= Fendo
:author: Marcos Cruz (programandala.net)
:revdate: 2020-11-29

// This file is part of Fendo
// http://programandala.net/en.program.fendo.html

// Last modified 202011292026

// tag::description[]

== Description

Fendo is a static website generator written in
http://forth-standard.org[Forth] with
http://gnu.org/software/gforth[Gforth].

Some features:

- Every source page is an independent Forth program that builds its
  HTML target.
- Actual Forth code can be embedded in source pages and design
  templates.
- Support for several markups (native, Asciidoctor, Markdown, HTML).
- Support for multilingual sites.
- Many addons for specific needs.
- Redirections.
- Nestable page shortcuts.
- Fully customizable.

Home page: http://programandala.net/en.program.fendo.html

// end::description[]

// tag::history[]

== History of the code

- 2012: The development of Fendo started in order to replace two
  previous website generators written by the author (one of them
  written in Forth, the other one in PHP) with a new one combining the
  best features of both of them.

- 2017-02-08: A local Git repository was created from all of the
  development backups, in order to resume the development and prepare
  the first public release.

- 2020-03-28: The repository was uploaded to GitHub.

- 2020-11-29: The repository was converted from Git to
  http://fossil-scm.org[Fossil], wich will be used to continue the
  development. GitHub will be used only as a mirror, exported and
  uploaded from the Fossil repository.

// end::history[]

// tag::status[]

== Current status

Fendo is very stable and is regulary improved, after the requirements
of the author's websites it already powers.

Since 2014, two websites were migrated from previous engines to
Fendo, and two more were created directly in it. At the time of writing
(2020-11) one more website is being migrated and two more are waiting.

The source code is well documented, but specific usage documentation
is still missing. A full manual with a complete glossary will be built
automatically from the sources.

Releases A-00..A-05 are internal, not recommended. 

The current version under development is 0.6.0, which will be
considered the first public version.

== The name

Fendo stands for "Forth Engine for Net DOcuments". Also,
http://vortaro.net/#fendo["fendo"] is the Esperanto word for "slot",
in the sense "a narrow depression, perforation, or aperture".

// end::status[]
